name: Weekly Fixture Update

on:
  schedule:
    - cron: '0 6 * * 1'
  workflow_dispatch:

jobs:
  update-fixtures:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Run update script
      run: node update-fixtures.js

    - name: Commit and push changes
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add fixtures.js
        git commit -m "Weekly update of match predictions"
        git push
